export const ADD_BUDGET_CLICK = 'ADD_BUDGET_CLICK';
export const ADD_BUDGET_REQUEST = 'ADD_BUDGET_REQUEST';
export const ADD_BUDGET_SUCCESS = 'ADD_BUDGET_SUCCESS';
export const ADD_BUDGET_FAILED = 'ADD_BUDGET_FAILED';

export const REMOVE_BUDGET_CLICK = 'REMOVE_BUDGET_CLICK';
export const REMOVE_BUDGET_REQUEST = 'REMOVE_BUDGET_REQUEST';
export const REMOVE_BUDGET_SUCCESS = 'REMOVE_BUDGET_SUCCESS';
export const REMOVE_BUDGET_FAILED = 'REMOVE_BUDGET_FAILED';

export const UPDATE_BUDGET_CLICK = 'UPDATE_BUDGET_CLICK';
export const UPDATE_BUDGET_REQUEST = 'UPDATE_BUDGET_REQUEST';
export const UPDATE_BUDGET_SUCCESS = 'UPDATE_BUDGET_SUCCESS';
export const UPDATE_BUDGET_FAILED = 'UPDATE_BUDGET_FAILED';

export const MOVE_BUDGET = 'MOVE_BUDGET';

export const ADD_TRANSACTION_CLICK = 'ADD_TRANSACTION_CLICK';
export const ADD_TRANSACTION_REQUEST = 'ADD_TRANSACTION_REQUEST';
export const ADD_TRANSACTION_SUCCESS = 'ADD_TRANSACTION_SUCCESS';
export const ADD_TRANSACTION_FAILED = 'ADD_TRANSACTION_FAILED';

export const UPDATE_TRANSACTION_CLICK = 'UPDATE_TRANSACTION_CLICK';

export const ADD_CATEGORY_CLICK = 'ADD_CATEGORY_CLICK';
export const ADD_CATEGORY_REQUEST = 'ADD_CATEGORY_REQUEST';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAILED = 'ADD_CATEGORY_FAILED';

export const REMOVE_CATEGORY_CLICK = 'REMOVE_CATEGORY_CLICK';
export const REMOVE_CATEGORY_REQUEST = 'REMOVE_CATEGORY_REQUEST';
export const REMOVE_CATEGORY_SUCCESS = 'REMOVE_CATEGORY_SUCCESS';
export const REMOVE_CATEGORY_FAILED = 'REMOVE_CATEGORY_FAILED';

export const UPDATE_CATEGORY_CLICK = 'UPDATE_CATEGORY_CLICK';
export const UPDATE_CATEGORY_REQUEST = 'UPDATE_CATEGORY_REQUEST';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAILED = 'UPDATE_CATEGORY_FAILED';

export const MOVE_CATEGORY = 'MOVE_CATEGORY';
